version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: permify
      POSTGRES_PASSWORD: permify
      POSTGRES_DB: permify
    ports:
      - "5432:5432"
    volumes:
      - permify-data:/var/lib/postgresql/data

  permify:
    image: permify/permify
    environment:
      DATABASE_URL: postgres://permify:permify@database:5432/permify
    ports:
      - "3476:3476"
    command: "serve"
    depends_on:
      - database

volumes:
  permify-data:
